#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Clean functions

cleanCase0
rm -rf logs residuals.png

#------------------------------------------------------------------------------
