#!/bin/bash

# Run the baseline case
cd baseline_foam
./run
cd ../

# Get the "truth" and create observations
cd truth_foam
./run
cd ../
./observations.py

# Create the covairance matrix (enforcing boundary conditions) and KL modes
./klmodes.py

# Create mesh and 0 directory for the foam case 
cd ../foam
cp -r 0.orig 0
blockMesh
cd -

