#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Run functions

restore0Dir
runApplication blockMesh
runApplication $(getApplication)
postProcess -func sampleDict 

