#!/usr/bin/env bash

# Possible usage:
#   >>> nohup ./run &
#
# To monitor:
#   >>> tail -f dafi.log

START=$(date +%s.%N)

dafi dafi.in &> dafi.log

END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo $DIFF  > .time
