#!/bin/sh

# cd ${0%/*} || exit 1
# . $WM_PROJECT_DIR/bin/tools/CleanFunctions
rm -r 1 2 3 4
rm log.*
# cleanCase0
# rm -f 0.orig/g1

#------------------------------------------------------------------------------
