#!/usr/bin/env bash
# Copyright 2018 Virginia Polytechnic Institute and State University.

rm -rf results*
rm -rf debug*
rm -rf *.log
rm -rf .time
#rm -rf .dafi_ver

# if dafi failed:
rm -rf sample_*
