#!/bin/bash
#
# This pre-commit hook tests that:
#   * the documentation builds,
#   * all Python files pass pep8, and
#   * the unit tests pass.
# Copy to: .git/hooks
#

# documentation
echo "Checking documentation build..."
res=$(DJANGO_SETTINGS_MODULE=###PROJECT###.settings bin/sphinx-build -q -E -w errors.log -b html -d build/doctrees source build/html 2> /dev/null)
if test -s errors.log; then  # if errors.log exists and isn't empty, then there's some errors
    echo "[error]  Blocking commit, found errors while building documentation:"
    cat errors.log
    rm -f errors.log
    exit 1
else
    echo "[success]  Documentation built without error."
fi
rm -f errors.log


# pep8
files=`git diff --name-only --cached --diff-filter=AMRd -- *.py`
for file in $files
do
    autopep=$(autopep8 -d $file)
    if [[ -z $autopep ]]
    then
        echo "[success] PEP8 passed."
    else
        echo "[error] PEP8 did not pass."
        echo "        File: $file"
        #echo "$autopep" | colordiff
        exit 1
    fi
done


# unittest
`python -m unittest discover -p "test_*.py"`
if [[ $? = 0 ]]
then
    echo "[succes] Unit tests passed."
else
    echo "[error] Unit  tests did not pass."
    exit 1
fi

