# type "make" command in HWnix to create mets.pdf file 
all:
	pdflatex HW
	bibtex HW
	pdflatex HW
	pdflatex HW

clean:
	(rm -rf *.spl *.out *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *blg)
