#!/bin/sh

cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# restore0Dir
runApplication blockMesh
runApplication $(getApplication)
result=$?
postProcess -func 'grad(U)'
mv log.$(getApplication) log.primal

exit $result

#------------------------------------------------------------------------------
